name: Usando variaveis de ambiente

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ENV_WORKFLOW: "Valor WORKFLOW"

jobs:
  teste-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor JOB teste-env"

    steps:
      - name: Exexução
        env:
          ENV_ACTION: "Valor ACTION - Execução"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"

      - name: Exexução 2
        env:
          ENV_ACTION: "Valor ACTION - SegundaExecução"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"

  teste-env2:
    runs-on: ubuntu-latest
    needs: [teste-env]
    env:
      ENV_JOB: "Valor JOB Segundo teste-env"

    steps:
      - name: Exexução
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
